// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MetaData
{
    public partial class MonthlyDataLogging
    {
        public string ApplicationName { get; set; }
        public string RequestingSystem { get; set; }
        public string ApiMethod { get; set; }
        public string RequestingStartDt { get; set; }
        public string RequestingEndDt { get; set; }
        public string ErrorMessage { get; set; }
        public string RequestMessage { get; set; }
        public string ResponseMessage { get; set; }
        public string Debug1 { get; set; }
        public string Debug2 { get; set; }
        public string ReturnCode { get; set; }
        public int TransactionId { get; set; }
    }
}