// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MetaData
{
    public partial class TrafficDataMonthly
    {
        public int CalendarMonthIndex { get; set; }
        public string CalendarMonth { get; set; }
        public int CalendarYear { get; set; }
        public int? MonthlyDataIn { get; set; }
        public int? MonthlyDataOut { get; set; }
    }
}