// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MetaData
{
    public partial class TrafficDataDaily
    {
        public int CalendarDay { get; set; }
        public string CalendarWeekDay { get; set; }
        public int CalendarMonthIndex { get; set; }
        public string CalendarMonth { get; set; }
        public int CalendarYear { get; set; }
        public int? DailyDataIn { get; set; }
        public int? DailyDataOut { get; set; }
    }
}